[project]
name = "champsim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AnirudhG07", email = "anirudhgupta@iisc.ac.in" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
]

[project.scripts]
champsim = "champsim:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
